<?php

$apikey = "rzp_test_nKSIozGBHfEBX8";

?>

<script src="https://code"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * 1000; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END'; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Privilege Holidays"
    data-description="Anywhere Holidays"
    data-image="https://cdn.dribbble.com/users/3154158/screenshots/7931401/srk_54_birthday_4x.jpg"
    data-prefill.name="<?php echo $_POST['name'] * 100; ?>"
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>